from sqlalchemy import Column, Integer, SmallInteger, String, Boolean, DateTime, Date, Numeric, Enum, Text, ForeignKey, func
from app.core.database import Base

class BanquePartenaire(Base):
    __tablename__ = "banques_partenaires"
    id_banque          = Column(Integer, primary_key=True, autoincrement=True)
    code_banque        = Column(String(20), nullable=False, unique=True)
    nom_banque         = Column(String(100), nullable=False)
    logo_url           = Column(String(255), nullable=True)
    description        = Column(Text, nullable=True)
    montant_min        = Column(Numeric(12,2), nullable=False, default=50000)
    montant_max        = Column(Numeric(12,2), nullable=False, default=5000000)
    taux_interet_min   = Column(Numeric(5,2), nullable=False, default=5)
    taux_interet_max   = Column(Numeric(5,2), nullable=False, default=20)
    duree_min_semaines = Column(Integer, nullable=False, default=4)
    duree_max_semaines = Column(Integer, nullable=False, default=104)
    conditions_texte   = Column(Text, nullable=True)
    score_min_requis   = Column(Integer, nullable=False, default=50)
    plan_requis        = Column(Enum("pro","premium"), nullable=False, default="premium")
    actif              = Column(Boolean, nullable=False, default=True)
    ordre_affichage    = Column(Integer, nullable=False, default=99)

class MicroCredit(Base):
    __tablename__ = "micro_credits"
    id_credit             = Column(Integer, primary_key=True, autoincrement=True)
    id_emprunteur         = Column(Integer, ForeignKey("utilisateurs.id_utilisateur", ondelete="RESTRICT"), nullable=False, index=True)
    id_banque             = Column(Integer, ForeignKey("banques_partenaires.id_banque"), nullable=False)
    montant_demande       = Column(Numeric(12,2), nullable=False)
    duree_semaines        = Column(SmallInteger, nullable=False)
    objet_credit          = Column(String(255), nullable=True)
    motif_demande         = Column(Text, nullable=True)
    montant_accorde       = Column(Numeric(12,2), nullable=True)
    taux_interet          = Column(Numeric(5,2), nullable=False, default=5)
    score_ml_decision     = Column(Integer, nullable=True)
    motif_refus           = Column(Text, nullable=True)
    montant_total_du      = Column(Numeric(12,2), nullable=True)
    montant_rembourse     = Column(Numeric(12,2), nullable=False, default=0)
    mensualite            = Column(Numeric(12,2), nullable=True)
    nb_echeances          = Column(Integer, nullable=True)
    contrat_pdf_url       = Column(String(500), nullable=True)
    signature_date        = Column(DateTime, nullable=True)
    signature_validee     = Column(Boolean, nullable=False, default=False)
    approuve_par          = Column(Integer, nullable=True)
    nb_relances_envoyees  = Column(Integer, nullable=False, default=0)
    date_derniere_relance = Column(DateTime, nullable=True)
    statut                = Column(Enum("demande","en_attente","approuve","refuse","en_cours","rembourse","en_retard"), nullable=False, default="demande", index=True)
    date_demande          = Column(DateTime, nullable=False, server_default=func.now())
    date_decision         = Column(DateTime, nullable=True)
    date_debut            = Column(Date, nullable=True)
    date_echeance         = Column(Date, nullable=True)
